/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "simpleMath_tests.ts" instead.
 */

#include <check.h>

#line 1 "simpleMath_tests.ts"
#include "simpleMath.h"

// checkmk simpleMath_tests.ts > simpleMath_tests.c
// gcc simpleMath.c simpleMath_tests.c -o tests -Wall -lm -lpthread -lrt -lcheck -Wall -std=c99 -g
// alternativ:
// gcc simpleMath.c simpleMath_tests.c -o tests -Wall -lm -lpthread -lrt -lcheck -lsubunit -Wall -std=c99 -g
// dann: ./tests

// use ck_assert_int_eq for integer comparison
// use ck_assert_str_eq for string comparison

START_TEST(is_negative_positive)
{
#line 13
    int test_num = 1;
    int result = is_negative(test_num);
    ck_assert_int_eq(0, result);
    
}
END_TEST

START_TEST(is_negative_negative)
{
#line 18
    int test_num = -1;
    int result = is_negative(test_num);
    ck_assert_int_eq(1, result);  
    
}
END_TEST

START_TEST(is_negative_zero)
{
#line 23
    int test_num = 0;
    int result = is_negative(test_num);
    ck_assert_int_eq(0, result);      

}
END_TEST

START_TEST(add_absolute_neg_neg)
{
#line 28
    int test_num_1 = -10;
    int test_num_2 = -13;
    int result = absolute_add(test_num_1, test_num_2);
    ck_assert_int_eq(23, result);
    
}
END_TEST

START_TEST(add_absolute_neg_pos)
{
#line 34
    int test_num_1 = -10;
    int test_num_2 = 15;
    int result = absolute_add(test_num_1, test_num_2);
    ck_assert_int_eq(25, result);    

}
END_TEST

START_TEST(add_absolute_pos_neg)
{
#line 40
    int test_num_1 = 9;
    int test_num_2 = -13;
    int result = absolute_add(test_num_1, test_num_2);
    ck_assert_int_eq(22, result);

}
END_TEST

START_TEST(add_absolute_pos_pos)
{
#line 46
    int test_num_1 = 10;
    int test_num_2 = 10;
    int result = absolute_add(test_num_1, test_num_2);
    ck_assert_int_eq(20, result);    

}
END_TEST

START_TEST(absolute_neg)
{
#line 52
    int test_num = -10;
    int result = absolute(test_num);
    ck_assert_int_eq(10, result); 

}
END_TEST

START_TEST(absolute_pos)
{
#line 57
    int test_num = 5;
    int result = absolute(test_num);
    ck_assert_int_eq(5, result); 
    
}
END_TEST

START_TEST(absolute_zero)
{
#line 62
    int test_num = 0;
    int result = absolute(test_num);
    ck_assert_int_eq(0, result);     
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, is_negative_positive);
    tcase_add_test(tc1_1, is_negative_negative);
    tcase_add_test(tc1_1, is_negative_zero);
    tcase_add_test(tc1_1, add_absolute_neg_neg);
    tcase_add_test(tc1_1, add_absolute_neg_pos);
    tcase_add_test(tc1_1, add_absolute_pos_neg);
    tcase_add_test(tc1_1, add_absolute_pos_pos);
    tcase_add_test(tc1_1, absolute_neg);
    tcase_add_test(tc1_1, absolute_pos);
    tcase_add_test(tc1_1, absolute_zero);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
