/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "Dateien/tag6/taschenrechner2/loesung/taschenrechner2_tests.ts" instead.
 */

#include <check.h>

#line 1 "Dateien/tag6/taschenrechner2/loesung/taschenrechner2_tests.ts"
#include "taschenrechner2.h"

// checkmk taschenrechner2_tests.ts > taschenrechner2_tests.c
// gcc taschenrechner2.c taschenrechner2_tests.c -o tests -Wall -lm -lpthread -lrt -lcheck -Wall -std=c99 -g -fprofile-arcs -ftest-coverage


START_TEST(calc_x_equals_y)
{
#line 8
    int x = 5;
    int y = 5;
    int interval = 1;
    int divisor = 1;
    ck_assert_int_eq(calc(x, y, interval, divisor), 5);

}
END_TEST

START_TEST(calc_only_x_and_y)
{
#line 15
    int x = 1;
    int y = 5;
    int interval = 1;
    int divisor = 1;
    ck_assert_int_eq(calc(x, y, interval, divisor), 120);

}
END_TEST

START_TEST(calc_x_equals_y_interval_5)
{
#line 22
    int x = 10;
    int y = 10;
    int interval = 5;
    int divisor = 1;
    ck_assert_int_eq(calc(x, y, interval, divisor), 10);

}
END_TEST

START_TEST(calc_x_and_y_interval_3)
{
#line 29
    int x = 10;
    int y = 13;
    int interval = 3;
    int divisor = 1;
    ck_assert_int_eq(calc(x, y, interval, divisor), 130);


}
END_TEST

START_TEST(calc_x_equals_y_divisor_10)
{
#line 37
    int x = 1000;
    int y = 1000;
    int interval = 1;
    int divisor = 10;
    ck_assert_int_eq(calc(x, y, interval, divisor), 100);

}
END_TEST

START_TEST(calc_x_equals_y_divisor_3)
{
#line 44
    int x = 1000;
    int y = 1000;
    int interval = 1;
    int divisor = 3;
    ck_assert_int_eq(calc(x, y, interval, divisor), 333);

}
END_TEST

START_TEST(calc_all_options_together)
{
#line 51
    int x = 1;
    int y = 10;
    int interval = 2;
    int divisor = 5;
    ck_assert_int_eq(calc(x, y, interval, divisor), 189);


    
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, calc_x_equals_y);
    tcase_add_test(tc1_1, calc_only_x_and_y);
    tcase_add_test(tc1_1, calc_x_equals_y_interval_5);
    tcase_add_test(tc1_1, calc_x_and_y_interval_3);
    tcase_add_test(tc1_1, calc_x_equals_y_divisor_10);
    tcase_add_test(tc1_1, calc_x_equals_y_divisor_3);
    tcase_add_test(tc1_1, calc_all_options_together);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
