/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "Dateien/tag5/toUpper/loesung/toUpper_tests.ts" instead.
 */

#include <check.h>

#line 1 "Dateien/tag5/toUpper/loesung/toUpper_tests.ts"
#include "toUpper.h"
#include <string.h>

// checkmk toUpper_tests.ts > toUpper_tests.c
// gcc toUpper.c toUpper_tests.c -o tests -Wall -lm -lpthread -lrt -lcheck -Wall -std=c99 -g


START_TEST(to_upper_j_to_J)
{
#line 9
    char to_test[] = "j";
    to_upper(to_test);

    char res[] = "J";
    ck_assert_str_eq(to_test, res);


}
END_TEST

START_TEST(to_upper_Z_stays_Z)
{
#line 17
    char to_test[] = "Z";
    to_upper(to_test);

    char res[] = "Z";
    ck_assert_str_eq(to_test, res);


}
END_TEST

START_TEST(to_upper_longer_string_only_lower_case)
{
#line 25
    char to_test[] ="diesisteinlangerstring";
    to_upper(to_test);
    
    char res[] = "DIESISTEINLANGERSTRING";
    ck_assert_str_eq(to_test, res);


}
END_TEST

START_TEST(to_upper_longer_string_mixed_case)
{
#line 33
    char to_test[] ="DIeSISTeinLANGERstring";
    to_upper(to_test);
    
    char res[] = "DIESISTEINLANGERSTRING";
    ck_assert_str_eq(to_test, res);

}
END_TEST

START_TEST(to_upper_really_long_string)
{
#line 40
    char to_test[] ="abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz";
    to_upper(to_test);
    
    char res[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ";
    ck_assert_str_eq(to_test, res);


}
END_TEST

START_TEST(compare_ignore_case_true_short)
{
#line 48
    char string1[] = "Y";
    char string2[] = "y";
    ck_assert_int_eq(compare_ignorecase(string1, string2), 0);


}
END_TEST

START_TEST(compare_ignore_case_false_short)
{
#line 54
    char string1[] = "z";
    char string2[] = "y";
    ck_assert_int_eq(compare_ignorecase(string1, string2), 1);


}
END_TEST

START_TEST(compare_ignore_case_true_long)
{
#line 60
    char string1[] = "HALLOwelt";
    char string2[] = "halloWELT";
    ck_assert_int_eq(compare_ignorecase(string1, string2), 0);


}
END_TEST

START_TEST(compare_ignore_case_false_long)
{
#line 66
    char string1[] = "HALLOwelt";
    char string2[] = "WELThallo";
    ck_assert_int_eq(compare_ignorecase(string1, string2), 1);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, to_upper_j_to_J);
    tcase_add_test(tc1_1, to_upper_Z_stays_Z);
    tcase_add_test(tc1_1, to_upper_longer_string_only_lower_case);
    tcase_add_test(tc1_1, to_upper_longer_string_mixed_case);
    tcase_add_test(tc1_1, to_upper_really_long_string);
    tcase_add_test(tc1_1, compare_ignore_case_true_short);
    tcase_add_test(tc1_1, compare_ignore_case_false_short);
    tcase_add_test(tc1_1, compare_ignore_case_true_long);
    tcase_add_test(tc1_1, compare_ignore_case_false_long);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
